### ISSUE TITLE
iterating through images from an api

### ISSUE THREAD

**Issue by MSeaman** [MSeaman/final_project#2]
@harimohanraj89 @bigtone1284 @DrRobotmck @WilliamfShaw 

I'm trying to cycle through the pictures that come with each game result from my api.

```
   <%= @games['images'].each do |game| %>
      <%= link_to image_tag game['super_url'], style: 'height: 150px; width: 150px;' if game['super_url']  %>
   <% end %>
```

this code should go through each instance of 'images' and just give me the image of 'super_url'.
While i do get the pictures I want., I also get the url of all the other images as well.

**Comment by WilliamfShaw** [comment]
@MSeaman can you give us some more details about what youve tried to do to solve this issue?

**Comment by MSeaman** [comment]
well i tried adding an if statement at the end so that it would only display the image if it was 'super_url'...didnt work. not sure what else to do
